### ISSUE TITLE
AngelFoundation Share Calculations in AngelCentralBank.sol

### ISSUE THREAD

**Issue by tghdev** [bitcoinfriends/angel-contracts#1]
https://github.com/bitcoinfriends/angel-contracts/blob/c1b18cb0038378c22ae20bef8e55ede7fe750f6e/contracts/angel/AngelCentralBank.sol#L129

According to this calculation you get ca. 4.3 AngelTokens for every 10 AngelToken investors mint, because you subtract the numerator (30) from the denominator (100). In your [docs](https://docs.google.com/spreadsheets/d/1XcfoNxQsmHdSNknKSQAH77kE5VZNB3h0h6cOZZ6uQak/edit#gid=782442881) you state that your share is 3 for every 10 tokens investors mint.

Rewrite to: `_purchasedTokensWei * angelFoundationShareNumerator / angelFoundationShareDenominator`

**Comment by bitcoinfriends** [comment]
Hi tonisamja

I have discussed your comment with our developer and he has confirmed that this calculation is working as intended.

For every 100 Angel Tokens that are minted (in total) 70 tokens are distributed to investors and 30 tokens are sent to the AngelFoundation.

Can you please have a look again, but as far as what our developer says this is working exactly as planned and as we have outlined in all of our documentation.

We appreciate you taking time to review our smart contract! :)

Thank you!
