### ISSUE TITLE
Use of constant functions

### ISSUE THREAD

**Issue by z-zap** [bitcoinfriends/angel-contracts#2]
Line 65, Pausable.sol, 
```  
function getPaused() constant returns (bool) {
    return paused;
}
```

`getPaused()` should not be a `constant` function (as it does not _always_ return the same value) but instead should be a `view` function. 

`view` functions: Read from, but do not write to, the state
`pure` functions: Do not read from nor write to the state

You can read more about the differences here: https://ethereum.stackexchange.com/questions/25200/solidity-what-is-the-difference-between-view-and-constant
https://vomtom.at/pure-vs-view-vs-constant-functions/

In general, "getter" functions (in typical OOP terminology) should be `view` functions unless you are not reading the state either (there are not many cases where this is true), in which case you would use `pure`.

I'm going to list every instance of this I find here instead of opening new issues. 

Line 126, Manageable.sol,
```
  function isManagerAllowed()
```
similarly should be a `view` and not `constant` function;

Line 109, Manageable.sol,
```
 function isPermissionGranted()
```
same issue;

Line 99, Manageable.sol,
```
 function isManagerEnabled()
```
same issue;

Line 155, AngelCentralBank.sol
``` 
function calculatePurchasedTokens()
```
same issue;

Line 277, AngelCentralBank.sol
```
function calculateRefundedEthWithDiscount()
```
same issue;

Line 297, AngelCentralBank.sol
```
  function calculateRefundedEth()
```
same issue;

Line 344, AngelCentralBank.sol
```
  function calculateLandmarkPrice()
```
same issue;

**Comment by bitcoinfriends** [comment]
Hi zlgrube,

I have discussed your comment with the developer but his comment was as follows:

> "https://solidity.readthedocs.io/en/latest/contracts.html#function-modifiers
> 
> Constant is an alias to view.
> 
> He has misunderstand the docs."

We appreciate you taking time to review our smart contract!

Thank you! :)

**Comment by z-zap** [comment]
Ah, I have. I assumed constant was a deprecated pattern. Closing the issue~
